version: '2'
services:
  account-service:
    image: barrycommins/account-service
    ports:
      - "8080:8080"
  mysql:
    image: mysql:5.7
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=dbpass
     - MYSQL_DATABASE=dev