version: '2'
services:
  account-service:
    image: barrycommins/account-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
      - kafka
    links:
      - mysql
  discovery-service:
    image: barrycommins/discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  edge-service:
    image: barrycommins/edge-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  admin-server:
    image: barrycommins/admin-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  dashboard-server:
      image: barrycommins/microservices-dashboard
      ports:
        - "9190:9190"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - SERVER_PORT=9190
  mysql:
    image: mysql:5.7
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=dbpass
     - MYSQL_DATABASE=dev
  kafka:
    image: confluentinc/cp-kafka:3.1.0
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ADVERTISED_HOST_NAME=kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:3.1.0
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    ports:
      - "2181:2181"
  zipkin:
    image: openzipkin/zipkin
    environment:
      - SERVER_PORT=9411
      - KAFKA_ZOOKEEPER=zookeeper:2181
      - KAFKA_TOPIC=sleuth
    ports:
      - "9411:9411"
    links:
      - kafka
      - zookeeper