spring:
  application:
    name: account-service
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: root
    password: dbpass
    initialize: true
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: false